using System.Diagnostics;
using UnityEditor;

namespace SBG.Toolbelt.AppLinker.Editor
{
	/// <summary>
	/// DO NOT MODIFY THIS CLASS!
	/// Any code within the "LINKS" region is generated by App Linker to add context menus
	/// for your apps. It depends on the characters being in the right positions
	/// </summary>
	public class AppLinks
	{
		#region LINKS

		#endregion
	}
}